# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.4

# Default target executed when no arguments are given to make.
default_target: all

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/drexil/projects/escheme/main

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/drexil/projects/escheme/main

# Include the progress variables for this target.
include CMakeFiles/progress.make

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/drexil/projects/escheme/main/CMakeFiles $(CMAKE_ALL_PROGRESS)
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/drexil/projects/escheme/main/CMakeFiles 0

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean

# The main clean target
clean/fast: clean

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1

#=============================================================================
# Target rules for targets named escheme

# Build rule for target.
escheme: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 escheme

# fast build rule for target.
escheme/fast:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/build

# target to build an object file
src/achars.o:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/achars.o

# target to preprocess a source file
src/achars.i:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/achars.i

# target to generate assembly for a file
src/achars.s:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/achars.s

# target to build an object file
src/astrings.o:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/astrings.o

# target to preprocess a source file
src/astrings.i:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/astrings.i

# target to generate assembly for a file
src/astrings.s:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/astrings.s

# target to build an object file
src/atom.o:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/atom.o

# target to preprocess a source file
src/atom.i:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/atom.i

# target to generate assembly for a file
src/atom.s:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/atom.s

# target to build an object file
src/bnumbers.o:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/bnumbers.o

# target to preprocess a source file
src/bnumbers.i:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/bnumbers.i

# target to generate assembly for a file
src/bnumbers.s:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/bnumbers.s

# target to build an object file
src/booleans.o:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/booleans.o

# target to preprocess a source file
src/booleans.i:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/booleans.i

# target to generate assembly for a file
src/booleans.s:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/booleans.s

# target to build an object file
src/cnumbers.o:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/cnumbers.o

# target to preprocess a source file
src/cnumbers.i:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/cnumbers.i

# target to generate assembly for a file
src/cnumbers.s:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/cnumbers.s

# target to build an object file
src/cons.o:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/cons.o

# target to preprocess a source file
src/cons.i:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/cons.i

# target to generate assembly for a file
src/cons.s:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/cons.s

# target to build an object file
src/dyntypes.o:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/dyntypes.o

# target to preprocess a source file
src/dyntypes.i:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/dyntypes.i

# target to generate assembly for a file
src/dyntypes.s:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/dyntypes.s

# target to build an object file
src/environments.o:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/environments.o

# target to preprocess a source file
src/environments.i:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/environments.i

# target to generate assembly for a file
src/environments.s:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/environments.s

# target to build an object file
src/escm.o:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/escm.o

# target to preprocess a source file
src/escm.i:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/escm.i

# target to generate assembly for a file
src/escm.s:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/escm.s

# target to build an object file
src/input.o:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/input.o

# target to preprocess a source file
src/input.i:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/input.i

# target to generate assembly for a file
src/input.s:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/input.s

# target to build an object file
src/macros.o:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/macros.o

# target to preprocess a source file
src/macros.i:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/macros.i

# target to generate assembly for a file
src/macros.s:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/macros.s

# target to build an object file
src/main.o:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/main.o

# target to preprocess a source file
src/main.i:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/main.i

# target to generate assembly for a file
src/main.s:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/main.s

# target to build an object file
src/output.o:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/output.o

# target to preprocess a source file
src/output.i:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/output.i

# target to generate assembly for a file
src/output.s:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/output.s

# target to build an object file
src/ports.o:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/ports.o

# target to preprocess a source file
src/ports.i:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/ports.i

# target to generate assembly for a file
src/ports.s:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/ports.s

# target to build an object file
src/primitives.o:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/primitives.o

# target to preprocess a source file
src/primitives.i:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/primitives.i

# target to generate assembly for a file
src/primitives.s:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/primitives.s

# target to build an object file
src/procedures.o:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/procedures.o

# target to preprocess a source file
src/procedures.i:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/procedures.i

# target to generate assembly for a file
src/procedures.s:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/procedures.s

# target to build an object file
src/promises.o:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/promises.o

# target to preprocess a source file
src/promises.i:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/promises.i

# target to generate assembly for a file
src/promises.s:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/promises.s

# target to build an object file
src/srfi.o:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/srfi.o

# target to preprocess a source file
src/srfi.i:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/srfi.i

# target to generate assembly for a file
src/srfi.s:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/srfi.s

# target to build an object file
src/symbols.o:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/symbols.o

# target to preprocess a source file
src/symbols.i:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/symbols.i

# target to generate assembly for a file
src/symbols.s:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/symbols.s

# target to build an object file
src/tst.o:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/tst.o

# target to preprocess a source file
src/tst.i:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/tst.i

# target to generate assembly for a file
src/tst.s:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/tst.s

# target to build an object file
src/utils.o:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/utils.o

# target to preprocess a source file
src/utils.i:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/utils.i

# target to generate assembly for a file
src/utils.s:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/utils.s

# target to build an object file
src/vectors.o:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/vectors.o

# target to preprocess a source file
src/vectors.i:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/vectors.i

# target to generate assembly for a file
src/vectors.s:
	$(MAKE) -f CMakeFiles/escheme.dir/build.make CMakeFiles/escheme.dir/src/vectors.s

# Help Target
help::
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... escheme"
	@echo "... rebuild_cache"
	@echo "... src/achars.o"
	@echo "... src/achars.i"
	@echo "... src/achars.s"
	@echo "... src/astrings.o"
	@echo "... src/astrings.i"
	@echo "... src/astrings.s"
	@echo "... src/atom.o"
	@echo "... src/atom.i"
	@echo "... src/atom.s"
	@echo "... src/bnumbers.o"
	@echo "... src/bnumbers.i"
	@echo "... src/bnumbers.s"
	@echo "... src/booleans.o"
	@echo "... src/booleans.i"
	@echo "... src/booleans.s"
	@echo "... src/cnumbers.o"
	@echo "... src/cnumbers.i"
	@echo "... src/cnumbers.s"
	@echo "... src/cons.o"
	@echo "... src/cons.i"
	@echo "... src/cons.s"
	@echo "... src/dyntypes.o"
	@echo "... src/dyntypes.i"
	@echo "... src/dyntypes.s"
	@echo "... src/environments.o"
	@echo "... src/environments.i"
	@echo "... src/environments.s"
	@echo "... src/escm.o"
	@echo "... src/escm.i"
	@echo "... src/escm.s"
	@echo "... src/input.o"
	@echo "... src/input.i"
	@echo "... src/input.s"
	@echo "... src/macros.o"
	@echo "... src/macros.i"
	@echo "... src/macros.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/output.o"
	@echo "... src/output.i"
	@echo "... src/output.s"
	@echo "... src/ports.o"
	@echo "... src/ports.i"
	@echo "... src/ports.s"
	@echo "... src/primitives.o"
	@echo "... src/primitives.i"
	@echo "... src/primitives.s"
	@echo "... src/procedures.o"
	@echo "... src/procedures.i"
	@echo "... src/procedures.s"
	@echo "... src/promises.o"
	@echo "... src/promises.i"
	@echo "... src/promises.s"
	@echo "... src/srfi.o"
	@echo "... src/srfi.i"
	@echo "... src/srfi.s"
	@echo "... src/symbols.o"
	@echo "... src/symbols.i"
	@echo "... src/symbols.s"
	@echo "... src/tst.o"
	@echo "... src/tst.i"
	@echo "... src/tst.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
	@echo "... src/vectors.o"
	@echo "... src/vectors.i"
	@echo "... src/vectors.s"



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0

